name: '⭐ 기능 요청'
description: '새로운 기능이나 개선사항을 제안합니다.'
title: '[Feature]'
labels:
  - 'enhancement'
body:
  - type: markdown
    attributes:
      value: '이슈를 입력하기 전에 [이슈 리스트](https://github.com/Airdnd-05/vite-airdnd/issues)에 중복된 이슈가 있는지 확인해주세요.'
  - type: textarea
    id: feature-description
    attributes:
      label: '기능 설명'
      description: '추가 기능 또는 개선 사항을 설명해주세요.'
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: '제안 이유'
      description: '추가 기능 또는 개선 사항이 필요하게 된 이유를 설명해주세요.'
  - type: textarea
    id: alternatives
    attributes:
      label: '대안'
      description: '고려하고 있는 대안이 있다면 설명해주세요.'
  - type: textarea
    id: additional-context
    attributes:
      label: '추가 사항'
      description: '추가로 설명할 사항이 있다면 입력해주세요.'
  - type: markdown
    attributes:
      value: 이슈 하나 당 하나의 제안만 해주세요.
